CREATE TABLE IF NOT EXISTS TODOS (
    ID	INTEGER PRIMARY KEY	NOT NULL AUTO_INCREMENT,
    COMPLETED	BOOLEAN NULL,
    DESCRIPTION	VARCHAR(255) NULL,
    TITLE	VARCHAR(255) NULL
);

CREATE SEQUENCE IF NOT EXISTS TODOS_SEQ AS INTEGER START WITH 6;